name: Linting

on: [push]

jobs:
  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "lts/hydrogen"

      - run: rm -rf node_modules
      - run: yarn install

      - run: yarn lint:prettier-check

  eslint:
    name: ESlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "lts/hydrogen"

      - run: rm -rf node_modules
      - run: yarn install

      - run: yarn lint:eslint-check
